### ISSUE TITLE
最好在 readme 中说明，模块并不是真正的检测字符编码

### ISSUE THREAD

**Issue by sailxjx** [node-modules/charset#5]
模块很不错，对于大部分 http 请求来说已经够用了，但是最好能说明一下工作原理只是检测了 header 中和 encoding 声明，没有真正做字符检测，以免被误用。

或者给一个兼容的解决办法， [stackoverflow](http://stackoverflow.com/questions/12326688/node-js-scrape-encoding) 上面有个不错的例子：

```javascript
request.get({url: 'http://www.example.com', encoding: 'binary'}, function(err, res, body) {
    enc = charset(res.headers, body)
    enc = enc or jchardet.detect(body).encoding.toLowerCase()
    if enc != 'utf-8'
        iconv = new Iconv(enc, 'UTF-8//TRANSLIT//IGNORE')
        html = iconv.convert(new Buffer(body, 'binary')).toString('utf-8')
    console.log(body);
});
```

**Comment by fengmk2** [comment]
Good point.

**Comment by fengmk2** [comment]
[jschardet](https://github.com/aadsm/jschardet)

**Comment by sailxjx** [comment]
@fengmk2 真迅速，例子里有一些错误在 pr 里提了，https://github.com/node-modules/charset/pull/6， 看一下吧
